#! /bin/sh
./EtcStartup
echo "Copying 'etc' files for powered Telescope Simulator"
cp -f CilSim.map Cil.map
cp -f LogSim.cfg Log.cfg
cp -f PmmSimPower.cfg Pmm.cfg
cp -f WmsSimPower.cfg Wms.cfg
cp -f CmtSimScc.cfg      CmtScc.cfg
cp -f CmtSimMcc.cfg      CmtMcc.cfg
cp -f CmtSimAcc.cfg      CmtAcc.cfg
cp -f CmtSimAzm.cfg      CmtAzm.cfg
cp -f CmtSimAlt.cfg      CmtAlt.cfg
cp -f CmtSimRot.cfg      CmtRot.cfg
cp -f CmtSimAmn.cfg      CmtAmn.cfg
cp -f CmtSimOcc.cfg      CmtOcc.cfg
cp -f CmtSimSys.cfg      CmtSys.cfg
#cp -f SimCctScc.cfg      CctScc.cfg
#cp -f SimCctMcc.cfg      CctMcc.cfg
cp -f SimCctAcc.cfg      CctAcc.cfg
cp -f SimCctAzm.cfg      CctAzm.cfg
cp -f SimCctAlt.cfg      CctAlt.cfg
cp -f SimCctRot.cfg      CctRot.cfg
cp -f SimCctCas.cfg      CctCas.cfg
cp -f SimCctNmi.cfg      CctNmi.cfg
cp -f SimCctAmn.cfg      CctAmn.cfg
cp -f OhgSim.cfg         Ohg.cfg
./EtcCleanup
echo "Done"

