#!/usr/bin/env bash

# Create the config files from the datum list files

for file in d*.lst
do
   cat confhead > temp
   cat $file | sed 's/,/, /g'>> temp
   cat conftail >> temp
   newfile=${file%.*}.cfg
   echo $newfile
   cat temp > $newfile
   rm temp
done
