/*******************************************************************************
**
**       Copyright (c) Telescope Technologies Limited (TTL) 2004.
** 
** Filename: 
**    Dht.h
**
** Purpose:
**    Public header file for Dummy Heartbeat Task (DHT).
**
** Description:
**    This code has been written to conform to "TTL Coding Standard" v1.0.
**
** Traceability to Software Design: 
**    -
**
** Authors:
**    mjf : Martyn J. Ford (TTL)
**
** Version:
**    $Id: Dht.h,v 0.1 2004/06/30 11:13:53 mjf Exp $
**
** History:
**    $Log: Dht.h,v $
**    Revision 0.1  2004/06/30 11:13:53  mjf
**    Initial revision.
**
**
*******************************************************************************/

#ifndef DHT_H_DEFINED
#define DHT_H_DEFINED


/*
** Include files
*/

#include "TtlSystem.h"


/* Global data submitted to the SDB by the DHT */

typedef enum eDhtDataId_e
{

   D_DHT_DATAID_BOL = 0,               /* Beginning of data list */

   /* Generic datums */

   D_DHT_PROC_STATE = D_MCP_PROC_STATE,   /* DHT process state */
   D_DHT_AUTH_STATE = D_MCP_AUTH_STATE,   /* DHT authorisation state */
   D_DHT_SYS_REQUEST = D_MCP_SYS_REQUEST, /* DHT process state */
   D_DHT_APP_VERSION = D_MCP_APP_VERSION, /* DHT process state */

   D_DHT_DMD_SHUTDOWN,                    /* Shutdown command */

   D_DHT_DATAID_EOL                    /* End of list marker */

} eDhtDataId_t;

/* Services provided by the DHT */

typedef enum eDhtService_e
{
   E_DHT_HEARTBEAT = E_MCP_HEARTBEAT,  /* Heartbeat command */
   E_DHT_SHUTDOWN  = E_MCP_SHUTDOWN,   /* Shutdown command */
   E_DHT_SAFESTATE = E_MCP_SAFESTATE,  /* Safestate command */
   E_DHT_ACTIVATE  = E_MCP_ACTIVATE,   /* Activate command */

   E_DHT_SET_1     = E_MCP_SET_1,      /* Generic set command */
   E_DHT_GET_1     = E_MCP_GET_1,      /* Generic get command */

   E_DHT_EOL                           /* End-of-list marker */ 
} eDhtService_t;

/* Status and errors generated by the DHT */

typedef enum eDhtStatus_e
{

   E_DHT_ERR_GEN = STATUS_START( DHT ),/* Miscellaneous error */
   E_DHT_ERR_SETUP,                    /* Error performing setup */
   E_DHT_ERR_CIL_NAME,                 /* Error matching CIL name */
   E_DHT_ERR_CIL_RX,                   /* Unexpected CIL message received */
   E_DHT_ERR_HEARTBEATS,               /* Assuming safe-state due to heartbeat loss */
   E_DHT_ERR_COMMAND_LEN,              /* Error in length of incoming command */
   E_DHT_ERR_COMMAND,                  /* Error in incoming command */
   E_DHT_ERR_COMMAND_DATUM,            /* Error in datum of incoming command */

   E_DHT_ERR_EOL                       /* End of list marker */
} eDhtStatus_t;


#endif

/*
** EOF
*/


